SECOND = 1
SEC_IN_MINUTE = SECOND * 60
SEC_IN_HOUR = SEC_IN_MINUTE * 60
SEC_IN_DAY = SEC_IN_HOUR * 24

DAYS_IN_WEEK = 7
DAYS_IN_MONTH = 30
DAYS_IN_HALF_YEAR = 180

FORMAT_YYYY_MM_DD_HH_MM_SS = '%Y-%m-%d %H:%M:%S'
FORMAT_DD_MM_YYYY = '%d-%m-%Y'
FORMAT_HH_MM_SS = '%H:%M:%S'