SECOND = 1
MINUTE = SECOND * 60
HOUR = MINUTE * 60
DAY = HOUR * 24

DAYS_IN_HALF_YEAR = 180

FORMAT_YYYY_MM_DD_HH_MM_SS = '%Y-%m-%d %H:%M:%S'
FORMAT_DD_MM_YYYY = '%d-%m-%Y'
FORMAT_HH_MM_SS = '%H:%M:%S'