from google_sheets.types import T_SHEET_RANGE


DEFAULT_SHEET_NAME = 'entity_config!'
RANGE_BITRIX_FIELDS_TO_DB_TYPES: T_SHEET_RANGE = 'A3:C'

SHEET_BITRIX_FIELD_INDEX = 0
SHEET_PYTHON_TYPE_INDEX = 1
SHEET_DB_TYPE_INDEX = 2