DEFAULT_SHEET_NAME = 'entity_config!'
RANGE_BITRIX_FIELDS_TO_DB_TYPES = 'A3:C'
RANGE_METHODS_NAMES = 'G3:G'
RANGE_ENTITIES_CONFIG = 'G3:K14'

SHEET_BITRIX_FIELD_INDEX = 0
SHEET_PYTHON_TYPE_INDEX = 1
SHEET_DB_TYPE_INDEX = 2
